### ISSUE TITLE
Melodic support

### ISSUE THREAD

**Issue by jorgenfb** [ros-industrial/industrial_core#213] opened 2018-10-16 08:08 UTC
Currently the install instructions references melodic packages which are not available quote from http://wiki.ros.org/Industrial/Install:

```
   * Industrial core: `apt-get install ros-melodic-industrial-core`
   * ABB stack: `apt-get install ros-melodic-abb`
   * Universal robot stack: `apt-get install ros-melodic-universal-robot`
   * ros_canopen stack: `apt-get install ros-melodic-ros-canopen`
```

**Comment by gavanderhoorn** [comment] 2018-10-16 08:57
Duplicate of https://github.com/ros-industrial/ros_industrial_issues/issues/40.

**Comment by gavanderhoorn** [comment] 2018-10-16 08:57
This is an unfortunate result of using the `ROS_DISTRO` variable on that page.

See the referenced issue for more details.

**Closed as completed** 2018-10-16 08:57 UTC
